# Generated by Django 5.0.6 on 2024-08-26 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ciudad_Actual', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Ciudad Actual',
                'verbose_name_plural': 'Ciudad Actual',
            },
        ),
        migrations.CreateModel(
            name='Estado_Civil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EstadoCivil', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estado Civil',
            },
        ),
        migrations.CreateModel(
            name='Lugar_Nacimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Lugar', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Ciudad de Nacimiento',
                'verbose_name_plural': 'Ciudad de Nacimiento',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sexo_p', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexo',
            },
        ),
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.CharField(max_length=50)),
                ('Ciudad_Actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoDat.ciudad')),
                ('EstadoCivil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoDat.estado_civil')),
                ('Nombre_Lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoDat.lugar_nacimiento')),
                ('Sexo_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoDat.sexo')),
            ],
            options={
                'verbose_name': 'Datos Generales',
                'verbose_name_plural': 'Datos Generales',
            },
        ),
    ]
