# Generated by Django 5.0.6 on 2024-09-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoDat', '0004_alter_datos_estadocivil_alter_datos_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
